sudo: false
language: node_js

node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- node

os:
- linux
- osx

jobs:
  include:
  - stage: test
    os: linux
    node_js: node
    script: travis_retry npm run coverage
    after_success:
    - travis_retry npm install coveralls
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

