environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "Current"

install:
- ps: Install-Product node $env:nodejs_version

- appveyor-retry npm install -g npm@latest
- appveyor-retry npm install

test_script:
- appveyor-retry npm test

build: off
